# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=1024)),
                ('location', models.CharField(blank=True, max_length=1024)),
                ('poster', models.ImageField(blank=True, upload_to='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ConcertSetlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyd.Concert')),
            ],
            options={
                'ordering': ['concert', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GearType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
                ('pseudo', models.CharField(blank=True, max_length=64)),
                ('birth_date', models.DateField()),
                ('avatar', models.ImageField(upload_to='')),
                ('member_from', models.DateField()),
                ('member_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['birth_date'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('image', models.ImageField(upload_to='')),
                ('members', models.ManyToManyField(to='wyd.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('artwork', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RecordTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyd.Record')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('duration', models.DurationField()),
                ('lyrics', models.TextField(blank=True)),
                ('authors', models.ManyToManyField(related_name='authors', to='wyd.Member')),
                ('compositors', models.ManyToManyField(related_name='compositors', to='wyd.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('link', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='recordtrack',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyd.Song'),
        ),
        migrations.AddField(
            model_name='record',
            name='content',
            field=models.ManyToManyField(through='wyd.RecordTrack', to='wyd.Song'),
        ),
        migrations.AddField(
            model_name='member',
            name='roles',
            field=models.ManyToManyField(to='wyd.Role'),
        ),
        migrations.AddField(
            model_name='gear',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gears', to='wyd.Member'),
        ),
        migrations.AddField(
            model_name='gear',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wyd.GearType'),
        ),
        migrations.AddField(
            model_name='concertsetlist',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyd.Song'),
        ),
        migrations.AddField(
            model_name='concert',
            name='members',
            field=models.ManyToManyField(to='wyd.Member'),
        ),
        migrations.AddField(
            model_name='concert',
            name='setlist',
            field=models.ManyToManyField(through='wyd.ConcertSetlist', to='wyd.Song'),
        ),
    ]
