# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wyd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertSetlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='concert',
            name='set_list',
        ),
        migrations.AddField(
            model_name='concertsetlist',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyd.Concert'),
        ),
        migrations.AddField(
            model_name='concertsetlist',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyd.Song'),
        ),
        migrations.AddField(
            model_name='concert',
            name='setlist',
            field=models.ManyToManyField(through='wyd.ConcertSetlist', to='wyd.Song'),
        ),
    ]
