# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instrument',
            new_name='InstrumentType',
        ),
    ]
