# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyd', '0002_auto_20171122_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pseudo',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_until',
            field=models.DateField(blank=True),
        ),
    ]
