# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wyd', '0003_auto_20171122_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GearType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameModel(
            old_name='InstrumentType',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='avatar',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='member',
            name='instrument',
        ),
        migrations.AddField(
            model_name='concert',
            name='location',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='concert',
            name='poster',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='member',
            name='roles',
            field=models.ManyToManyField(to='wyd.Role'),
        ),
        migrations.AddField(
            model_name='record',
            name='artwork',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='song',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='wyd.Member'),
        ),
        migrations.AddField(
            model_name='song',
            name='compositors',
            field=models.ManyToManyField(related_name='compositors', to='wyd.Member'),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gear',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyd.Member'),
        ),
        migrations.AddField(
            model_name='gear',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wyd.GearType'),
        ),
    ]
