# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyd', '0004_auto_20171122_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
